-- MySQL Script generated by MySQL Workbench
-- ter 04 out 2022 21:38:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema show_do_espigao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema show_do_espigao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `show_do_espigao` ;
USE `show_do_espigao` ;

-- -----------------------------------------------------
-- Table `show_do_espigao`.`opcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_espigao`.`opcoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questao` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_opcoes_questoes1_idx` (`questao` ASC) VISIBLE,
  CONSTRAINT `fk_opcoes_questoes1`
    FOREIGN KEY (`questao`)
    REFERENCES `show_do_espigao`.`questoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_espigao`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_espigao`.`questoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `nivel` INT NOT NULL,
  `resposta_correta` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questoes_opcoes1_idx` (`resposta_correta` ASC) VISIBLE,
  CONSTRAINT `fk_questoes_opcoes1`
    FOREIGN KEY (`resposta_correta`)
    REFERENCES `show_do_espigao`.`opcoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `show_do_espigao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_espigao`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `chave_autenticacao_google` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `show_do_espigao`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `show_do_espigao`.`pontuacao` (
  `id` INT NOT NULL,
  `usuario` INT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`id`)
    REFERENCES `show_do_espigao`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
